[server]
# Optimize for Streamlit Cloud - More permissive settings
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
headless = true
runOnSave = false
fileWatcherType = "none" 

[browser]
# Disable some features that can cause issues
gatherUsageStats = false

[theme]
# Default theme
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "warning"

[client]
# Disable some client-side features that can cause issues
showErrorDetails = false
